name: ruff
version: v0.1.11
summary: An extremely fast Python linter, written in Rust.
# noinspection YAMLSchemaValidation
# https://youtrack.jetbrains.com/issue/PY-58754
description: |
  Ruff aims to be orders of magnitude faster than alternative tools while integrating more
  functionality behind a single, common interface.

  Ruff can be used to replace [Flake8](https://pypi.org/project/flake8/) (plus a variety of plugins), [`isort`](https://pypi.org/project/isort/),
  [`pydocstyle`](https://pypi.org/project/pydocstyle/), [`yesqa`](https://github.com/asottile/yesqa),
  [`eradicate`](https://pypi.org/project/eradicate/), [`pyupgrade`](https://pypi.org/project/pyupgrade/),
  and [`autoflake`](https://pypi.org/project/autoflake/), all while executing tens or hundreds of
  times faster than any individual tool.

  Ruff goes beyond the responsibilities of a traditional linter, instead functioning as an advanced
  code transformation tool capable of upgrading type annotations, rewriting class definitions, sorting
  imports, and more.
  
  N.B. snap confinement: The snap package for ruff is limited by default to accessing files in your home directory.

confinement: strict
base: core22
# The base that the builds run on - allows building for other architectures
build-base: core22
# Performance difference with xz vs lzo is small in this case, but provides
# a ~40% reduction in file size for a very frequently updating snap.
compression: xz
contact: https://github.com/lengau/ruff/issues
issues:
  - https://github.com/lengau/ruff-snap/issues
  - https://github.com/astral-sh/ruff/issues
source-code: https://github.com/astral-sh/ruff
website: https://github.com/astral-sh/ruff

build-packages:
  - curl

parts:
  rust-deps:  # TODO: This will no longer be needed with Snapcraft 8
    plugin: nil
    override-pull: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | \
      sh -s -- -y --no-modify-path --profile=minimal --default-toolchain stable
  ruff:
    after: [rust-deps]
    plugin: rust
    source: https://github.com/astral-sh/ruff
    source-type: git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    source-depth: 1
    rust-path: [crates/ruff_cli]
  flake8-to-ruff:
    after: [rust-deps]
    plugin: rust
    source: https://github.com/astral-sh/ruff
    source-type: git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    source-depth: 1
    rust-path: [crates/flake8_to_ruff]

apps:
  ruff:
    command: bin/ruff
    plugs:
      - home
      - removable-media
  flake8-to-ruff:
    command: bin/flake8-to-ruff
    plugs:
      - home
      - removable-media
