name: ruff
version: 0.5.1
summary: An extremely fast Python linter, written in Rust.
# noinspection YAMLSchemaValidation
# https://youtrack.jetbrains.com/issue/PY-58754
description: |
  Ruff aims to be orders of magnitude faster than alternative tools while integrating more
  functionality behind a single, common interface.

  - ⚡️ 10-100x faster than existing linters (like Flake8) and formatters (like Black)
  - 🐧 Installable via `snap`
  - 🛠️ `pyproject.toml` support
  - 🤝 Python 3.12 compatibility
  - ⚖️ Drop-in parity with Flake8, isort, and Black
  - 📦 Built-in caching, to avoid re-analyzing unchanged files
  - 🔧 Fix support, for automatic error correction (e.g., automatically remove unused imports)
  - 📏 Over 700 built-in rules, with native re-implementations of popular Flake8 plugins, like flake8-bugbear
  - ⌨️ First-party editor integrations for VS Code and more
  - 🌎 Monorepo-friendly, with hierarchical and cascading configuration

confinement: strict
base: core22
# The base that the builds run on - allows building for other architectures
build-base: core22
# Performance difference with xz vs lzo is small in this case, but provides
# a ~40% reduction in file size for a very frequently updating snap.
compression: xz
contact: https://github.com/lengau/ruff/issues
issues:
  - https://github.com/lengau/ruff-snap/issues
  - https://github.com/astral-sh/ruff/issues
source-code: https://github.com/astral-sh/ruff
website: https://github.com/astral-sh/ruff

architectures:
  - amd64
  - arm64
  - armhf
  - ppc64el
  - riscv64
  - s390x

parts:
  ruff:
    plugin: rust
    rust-path:
      - crates/ruff
    source: https://github.com/astral-sh/ruff
    source-type: git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    source-depth: 1
    stage:
      - bin/ruff
    organize:
      ruff: bin/ruff
  ruff-lsp:
    after: [ruff]
    plugin: python
    source: https://github.com/astral-sh/ruff-lsp
    source-type: git
    source-tag: v0.0.54  # LSP
    source-depth: 1
    override-build: |
      # Remove the ruff dependency since we're installing it ourselves.
      sed -i '/"ruff[<>=>~]=[0-9.]*",/d' pyproject.toml
      craftctl default
    build-environment:
      - PARTS_PYTHON_VENV_ARGS: --system-site-packages
    stage:
      - -bin/a*
      - -bin/Activate.ps1
      - -bin/pip*
      - -bin/python
      - -bin/python3.10
      - -bin/wheel
      - -lib/python3.10/site-packages/pip*
      - -lib/python3.10/site-packages/setuptools*
      - -lib/python3.10/site-packages/wheel*

apps:
  ruff:
    command: bin/ruff
    plugs:
      - home
      - removable-media
  lsp:
    command: bin/ruff-lsp
