name: ruff
version: 0.14.3
summary: An extremely fast Python linter, written in Rust.
# noinspection YAMLSchemaValidation
# https://youtrack.jetbrains.com/issue/PY-58754
description: |
  Ruff aims to be orders of magnitude faster than alternative tools while integrating more
  functionality behind a single, common interface.

  - ⚡️ 10-100x faster than existing linters (like Flake8) and formatters (like Black)
  - 🐧 Installable via `snap`
  - 🛠️ `pyproject.toml` support
  - 🤝 Python 3.12 compatibility
  - ⚖️ Drop-in parity with Flake8, isort, and Black
  - 📦 Built-in caching, to avoid re-analyzing unchanged files
  - 🔧 Fix support, for automatic error correction (e.g., automatically remove unused imports)
  - 📏 Over 700 built-in rules, with native re-implementations of popular Flake8 plugins, like flake8-bugbear
  - ⌨️ First-party editor integrations for VS Code and more
  - 🌎 Monorepo-friendly, with hierarchical and cascading configuration

confinement: strict
base: core24
# Performance difference with xz vs lzo is small in this case, but provides
# a ~40% reduction in file size for a very frequently updating snap.
compression: xz
contact: https://github.com/snapcrafters/ruff/issues
issues:
  - https://github.com/snapcrafters/ruff/issues
  - https://github.com/astral-sh/ruff/issues
source-code: https://github.com/astral-sh/ruff
website: https://github.com/astral-sh/ruff

package-repositories:
  - type: apt
    architectures: [$CRAFT_ARCH_BUILD_FOR]
    formats: [deb, deb-src]
    components: [main]
    suites: [noble, noble-updates, noble-backports]
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    url: http://ports.ubuntu.com/ubuntu-ports

platforms:
  armhf:
    build-on: [arm64, amd64]
    build-for: [armhf]

parts:
  ruff:
    plugin: rust
    rust-path:
      - crates/ruff
    source: https://github.com/astral-sh/ruff
    source-type: git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    source-depth: 1
    build-environment:
      # Build a static binary. Needed for armhf because of https://github.com/canonical/snapcraft/issues/5836
      - CARGO_BUILD_TARGET: armv7-unknown-linux-musleabihf
      - CARGO_TARGET_ARMV7_UNKNOWN_LINUX_MUSLEABIHF_LINKER: rust-lld
      - CARGO_CFG_TARGET_FEATURE: crt-static
      - CC: clang-20
      - CARGO_PROFILE_RELEASE_LTO: "off"
    build-packages:
      - libclang-20-dev
      - cmake
      - gcc-arm-linux-gnueabihf
      - libc6-dev-armhf-cross
      # Use clang for the armhf build so we can build for musl.
      - clang-20
      - musl-dev
      - musl-tools
    override-build: |
      rustup target add ${CARGO_BUILD_TARGET}
      craftctl default
      # manually install the ruff binary as its target dir differs
      install -Dvm755 ./target/${CARGO_BUILD_TARGET}/release/ruff "${CRAFT_PART_INSTALL}/bin/ruff"

apps:
  ruff:
    command: bin/ruff
    plugs:
      - home
      - removable-media
