name: Pull Request

on:
  pull_request:
    branches: [ "**" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: 🧪 Build snap
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 🧪 Build snap
        uses: snapcrafters/ci/test-snap-build@main
      - name: 🗒️ Run tests
        uses: snapcrafters/ci/run-tests@main
        with:
          test-script: ./test.sh
